using System;
using MySqlConnector;

namespace FixAdmin
{
    class Program
    {
        static void Main(string[] args)
        {
            string connectionString = "Server=localhost;Database=WholesaleDB;User=root;Password=NewPassword123;Port=3307;AllowUserVariables=True";
            
            // Hash generated by BCrypt for 'Test@123'
            string correctHash = BCrypt.Net.BCrypt.HashPassword("Test@123");

            using (var connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                using (var command = new MySqlCommand("UPDATE Users SET PasswordHash = @hash WHERE Role = 'Admin'", connection))
                {
                    command.Parameters.AddWithValue("@hash", correctHash);
                    int rows = command.ExecuteNonQuery();
                    Console.WriteLine($"Updated {rows} admin(s) with correct password hash.");
                }
            }
        }
    }
}
